# Project information
site_name: "Mega Python"
site_description: "Learn Python From Beginner to Advanced"
site_author: "Anil Kulkarni"
site_url: "https://www.megapython.org"

# # Repository
# repo_name: "megapython/megapython"
# repo_url: "https://github.com/megapython/megapython"

# Copyright
copyright: "Copyright &copy; 2020 Anil Kulkarni, Octallium Inc."

# Configuration
theme:
  name: "material"
  language: "en"
  logo: "images/megapython.png"
  favicon: "images/megapython.png"
  palette:
    primary: "white"
    accent: "indigo"
  font:
    text: "IBM Plex Sans"
    code: "Roboto Mono"
  feature:
    tabs: true

# Customization
extra:
  # manifest: "manifest.webmanifest"
  social:
    # - type: "github"
    #   link: "https://github.com/megapython"
    - type: "youtube"
      link: "https://www.youtube.com/channel/UCptVl5nZtCcx9SPOCqPnj7A?sub_confirmation=1"
    - type: "twitter"
      link: "https://twitter.com/mega_python"
    - type: "linkedin"
      link: "https://linkedin.com/company/megapython"

# Google Analytics
google_analytics:
  - "UA-121309781-2"
  - "auto"

# Plugins
plugins:
  - search

# Extensions
markdown_extensions:
  - meta
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Nav
nav:
  - Home: "index.md"
  - About:
      - "About": "about/about.md"
      # - "Contributing Content": "about/contribution.md"
  - Donate:
      - Donate: "donate.md"
  - Basics:
      - Introduction: "basics/introduction.md"
      - Installation: "basics/installation.md"
      - Variables: "basics/variables.md"
      - "Data Types": "basics/data-types.md"
      - Functions: "basics/functions.md"
      - "If Else": "basics/if-else.md"
      - "Static Typing": "basics/static-typing.md"
      - List: "basics/list.md"
      - Loops: "basics/loops.md"
      - Strings: "basics/strings.md"
      - Dictionary: "basics/dictionary.md"
      - Tuple: "basics/tuple.md"
      - Set: "basics/set.md"
      - Packages: "basics/packages.md"
      - "Object Oriented Programming": "basics/oop.md"
      - "File Handling": "basics/file-handling.md"
      - "Error Handling": "basics/error-handling.md"
  - Intermediate:
      - Introduction: "intermediate/introduction.md"
      - "List Comprehensions": "intermediate/list-comprehensions.md"
      - Lambda: "intermediate/lambda.md"
      - "Magic Methods": "intermediate/magic-methods.md"
      - "ABC Class": "intermediate/abc-class.md"
      - "Multi Threading": "intermediate/multi-threading.md"
      - "Async Await": "intermediate/async-await.md"
      - "Generators and Iterators": "intermediate/generators-iterators.md"
      - Testing: "intermediate/testing.md"
      - "Named Tuple": "intermediate/named-tuple.md"
      - "Functional Programming": "intermediate/functional-programming.md"
      - "Command Line Applications": "intermediate/cli.md"
      - "Regular Expressions": "intermediate/regular-expression.md"
      - Database: "intermediate/database.md"
      - Logging: "intermediate/logging.md"
      - "Introduction to HTTP": "intermediate/intro-http.md"
  - Django:
      - Introduction: "django/introduction.md"
      - Basics:
          - "Virutal Environment": "django/basics/virtual_environment.md"
          - Installation: "django/basics/installation.md"
      - "Django Rest Framework":
          - Introduction: "django/rest_framework/introduction.md"
  - Courses:
      - Courses: "courses/courses.md"

  - Subscribe:
      - Subscribe: "subscribe.md"
  - Contact:
      - Contact: "contact/contact.md"
